on:
  push:
  pull_request:
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        sbt: ["1.12.8", "2.0.0-RC10", "2.0.0-RC11"]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-java@v5
      with:
        distribution: temurin
        java-version: 17
    - uses: sbt/setup-sbt@v1
    - run: echo "sbt.version=${{ matrix.sbt }}" > project/build.properties
    - run: sbt "foo ; reload plugins ; foo ; reload return ; foo "
